---

    ##
    # Wordpress
#
- name: Wordpress
  subversion: repo=svn+http://core.svn.wordpress.org/tags/$wordpress_version dest=/var/www/wordpress
  tags: wordpress

- name: chown wp
  file: path=/var/www/wordpress recurse=yes owner=www-data group=www-data state=directory
  tags: wp_plugins
