---
# tasks file for wordpress

- name: Download wordpress
  get_url: url="https://wordpress.org/latest.tar.gz" dest=/tmp/wordpress.tar.gz validate_certs=no

- name: extract wordpress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www copy=no
  sudo: yes

- name: creating dir for /tmp/wordpress
  command: mkdir -p /tmp/wordpress

- name: get unique hash for wordpress
  get_url: url="https://api.wordpress.org/secret-key/1.1/salt/" dest=/tmp/wordpress/wp_salt

- name: setup the wordpress configuration file
  template: src=templates/wp-config.j2 dest=/tmp/wordpress/wp-config.php

- name: assemble the wordpress configuration file
  assemble: src=/tmp/wordpress dest=/var/www/wordpress/wp-config.php 

